#!/usr/bin/env bash

set -ex

scp goss.yaml pi@raspberrypi.local:~

ssh pi@raspberrypi.local "bash -ex" << EOF
     wget -qO ./goss https://github.com/bamarni/releases/raw/master/goss-arm64
     chmod +x goss
     sudo ./goss validate
     rm goss goss.yaml
     sudo modprobe configs
     zgrep BCM_VCIO=y /proc/config.gz
EOF
